server:
  port: 8001
spring:
  application:
    name: api-user-login
  redis:
    port: 7001
    host: 47.96.11.185
    database: 0
    password: qfedu123
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka

feign:
  hystrix:
    enabled: true
