server:
  port: 8066
spring:
  application:
    name: order-timeout-cancle
  rabbitmq:
    host: 47.96.11.185
    port: 5672
    virtual-host: host1
    username: zhangsan
    password: admin123
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka
feign:
  hystrix:
    enabled: true