server:
  port: 8066
spring:
  application:
    name: order-timeout-cancle
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka
feign:
  hystrix:
    enabled: true