spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      ## 如果后端项目服务器和数据库服务器不在同一台主机，则需要修改localhost为数据库服务器ip地址
      url: jdbc:mysql://localhost:3306/fmmall2?characterEncoding=utf-8
      username: root
      password: admin123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6390
#    host: 47.96.11.185
    host: 47.100.71.107
    database: 0
    password: admin123456
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.fmmall.entity

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error

redisson:
  addr:
    singleAddr:
#      host: redis://47.96.11.185:6379
      host: redis://47.100.71.107:6390
      password: admin123456
      database: 0